### PR TITLE
Fix: Generated AST library pops interfaces even in case of error

### PR DESCRIPTION
**Pull request by Yoric**

### CODE REVIEW

**Comment by arai-a** [comment]
what does "pops" mean here?

**Comment by Yoric** [comment]
The opposite of `push()`: remove latest inserted element.

**Comment by arai-a** [comment]
I don't understand the issue

**Comment by Yoric** [comment]
It's a combination of two things:

- `Path` asserts in a few places that we removed fields and interfaces in the reverse order in which they were added;
- when the serializer encounters an error (e.g. an i/o error), it bails out immediately, without removing fields/interfaces properly;
- by combining the above, we encounter a case in which an error in the dictionary triggers an assertion failure;
- I have tweaked our ast generator to fix this.

**Comment by Yoric** [comment]
Thank you :)

**Pull request merged**
