### PR TITLE
Resolves #305 - Implement a mechanism to cleanup `foo["bar"]` into `f…

### LINKED ISSUE #305: Implement a mechanism to cleanup foo["bar"] into foo.bar
Since we namespace strings and property keys separately, having both `foo["bar"]` and `foo.bar` in the same source hurts compression. We should have a mechanism to optionally clean this up.

I believe that the best place to do so is around the Shift parser.

### PR DESCRIPTION
**Pull request by Yoric**
…oo.bar`.

We implement this mechanism during Shift conversion. With this patch, the cleanup is enabled by default.

### CODE REVIEW

**Comment by RReverser** [comment]
Hmm how common is that case? Gut feeling teels me that conversion like this should live in a separate tool (like minifier) perhaps as it doesn't have much to do with BinaryAST itself...

**Comment by Yoric** [comment]
I agree that it should, ideally, live in a separate tool. I'm not sure how we could produce such a tool, at the moment, though, at least not with important refactoring. Do you have any idea?

Also, my objective with this patch was to let us test whether this improves compression, but I guess I can perform the tests without landing the patch.

**Comment by RReverser** [comment]
> I'm not sure how we could produce such a tool, at the moment, though, at least not with important refactoring.

I think this is already a feature of most popular minifiers, and I'd expect most popular assets to be minified regardless of BinaryAST.

E.g. with UglifyJS:

```
> echo 'x["bar"]' | uglifyjs --compress
x.bar;
```

**Comment by Yoric** [comment]
Yeah, I was thinking of the cases that cannot be represented easily within the JS syntax (e.g. `foo["several words & special characters"]`), but they are probably not very common :)

Let's forget about this PR for now.

**Pull request closed without merging**
