### PR TITLE
Doc: Second attempt to autobuild/publish documentation

### PR DESCRIPTION
**Pull request by Yoric**

### CODE REVIEW

**Comment by RReverser** [comment]
Can't leave comment on the actual line, because browser starts hanging, but: you probably still need to add nightly rustup before running `cargo +nightly doc`? Alternatively, just build docs with stable for now (without including external doc) and add nightly in a separate PR after this works.

**Comment by Yoric** [comment]
Ah, right, attempting to install nightly before deploying.

**Comment by RReverser** [comment]
```
error: Found argument '--features' which wasn't expected, or isn't valid in this context
	Did you mean to put '--features' after the subcommand 'bench'?
```

**Comment by RReverser** [comment]
https://github.com/binast/binjs-ref/pull/392

**Pull request merged**
